-- MySQL Script generated by MySQL Workbench
-- Sun Mar 23 19:47:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EquiMap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EquiMap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EquiMap` DEFAULT CHARACTER SET utf8 ;
USE `EquiMap` ;

-- -----------------------------------------------------
-- Table `EquiMap`.`Place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EquiMap`.`Place` ;

CREATE TABLE IF NOT EXISTS `EquiMap`.`Place` (
  `idPlace` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `imageLink` VARCHAR(5000) NULL,
  `wheelchairAccess` TINYINT NULL DEFAULT 0 COMMENT '0 - unknown\n1 - yes\n2 - no',
  `wheelchairAccessDescription` VARCHAR(200) NULL,
  `inductionLoop` TINYINT NULL DEFAULT 0,
  `inductionLoopDescription` VARCHAR(200) NULL,
  `description` VARCHAR(4000) NULL,
  `customerRating` TINYINT NULL COMMENT 'from 0 to 5, null - unknown; scraper didn\'t find data',
  `priceRange` TINYINT NULL,
  `contactNumber` VARCHAR(100) NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  PRIMARY KEY (`idPlace`),
  UNIQUE INDEX `idPlace_UNIQUE` (`idPlace` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
