-- MySQL Script generated by MySQL Workbench
-- Wed Apr  2 16:08:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EquiMap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EquiMap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EquiMap` DEFAULT CHARACTER SET utf8 ;
USE `EquiMap` ;

-- -----------------------------------------------------
-- Table `EquiMap`.`Place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EquiMap`.`Place` ;

CREATE TABLE IF NOT EXISTS `EquiMap`.`Place` (
  `Placecol` VARCHAR(45) NULL,
  `idPlace` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `formattedAddress` VARCHAR(500) NOT NULL,
  `photo` VARCHAR(5000) NULL,
  `wheelchairAccessibleParking` TINYINT(1) NULL,
  `wheelchairAccessibleEntrance` TINYINT(1) NULL,
  `wheelchairAccessibleRestroom` TINYINT(1) NULL,
  `wheelchairAccessDescription` VARCHAR(200) NULL,
  `inductionLoop` TINYINT(1) NULL DEFAULT 0,
  `inductionLoopDescription` VARCHAR(200) NULL,
  `description` VARCHAR(4000) NULL,
  `rating` TINYINT NULL COMMENT 'from 0 to 5, null - unknown;',
  `priceLevel` TINYINT NULL,
  `nationalPhoneNumber` VARCHAR(15) NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `regularOpeningHours` VARCHAR(1000) NULL,
  `delivery` TINYINT(1) NULL,
  `takeout` TINYINT(1) NULL,
  `dineIn` TINYINT(1) NULL,
  `outdoorSeating` TINYINT(1) NULL,
  `liveMusic` TINYINT(1) NULL,
  `allowsDogs` TINYINT(1) NULL,
  `goodForChildren` TINYINT(1) NULL,
  `goodForGroups` TINYINT(1) NULL,
  `goodForWatchingSports` TINYINT(1) NULL,
  `restroom` TINYINT(1) NULL,
  `reservable` TINYINT(1) NULL,
  `curbsidePickup` TINYINT(1) NULL,
  `menuForChildren` TINYINT(1) NULL,
  `acceptsCreditCards` TINYINT(1) NULL,
  `acceptsDebitCards` TINYINT(1) NULL,
  `acceptsCashOnly` TINYINT(1) NULL,
  `acceptsNfc` TINYINT(1) NULL,
  PRIMARY KEY (`idPlace`),
  UNIQUE INDEX `idPlace_UNIQUE` (`idPlace` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
